server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rainng_course?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#邮箱配置
#平台地址，这里用的是qq邮箱
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: guswnhufoomobgha
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: 503096576@qq.com

  #  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis
#    timeout: 86400
  jackson:
    # 返回格式化日期
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mvc:
      # 前端参数格式化
      format:
        # String格式化日期
        date: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/rainng_course

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rainng.coursesystem.model
logging:
  level:
    com.rainng.coursesystem.dao: debug